/**
 * js/app.js
 * Auto-generated by generate_site.py — edits here are overwritten on the
 * next run. Edit JS_APP_TEMPLATE in generate_site.py instead.
 *
 * Drives:
 *   - the always-visible nav (back button, template menu, font-size buttons)
 *   - fetching + injecting template/<slug>.html into #content
 *   - the welcome view’s Fuse-powered search (live from the 3ʳᵈ character)
 */

(function () {
  'use strict';

  // ---------------------------------------------------------------
  // Small helpers
  // ---------------------------------------------------------------

  var STORAGE_PREFIX = 'presentations:';

  function dbGet(key, fallback) {
    try {
      var raw = localStorage.getItem(STORAGE_PREFIX + key);
      return raw === null ? fallback : JSON.parse(raw);
    } catch (e) {
      return fallback;
    }
  }

  function dbSet(key, value) {
    try {
      localStorage.setItem(STORAGE_PREFIX + key, JSON.stringify(value));
    } catch (e) {
      /* ignore quota / privacy-mode errors */
    }
  }

  function escapeHtml(str) {
    var p = document.createElement('p');
    p.textContent = str == null ? '' : String(str);
    return p.innerHTML;
  }

  function debounce(fn, wait) {
    var timer;
    return function () {
      var args = arguments;
      clearTimeout(timer);
      timer = setTimeout(function () { fn.apply(null, args); }, wait);
    };
  }

  /* Mirrors the Python-side normalize_search_text() so indexed text and
     typed queries normalize the same way. */
  function normalizeQuery(str) {
    return String(str || '')
      .toLowerCase()
      .normalize('NFD')
      .replace(/[̀-ͯ]/g, '')
      .replace(/[^a-z0-9\s]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function isFileProtocol() {
    return location.protocol === 'file:';
  }

  // ---------------------------------------------------------------
  // Persistent DOM refs (these nodes are never replaced — only
  // #content's innerHTML changes, so anything inside #content must be
  // re-queried after each swap instead of cached up here)
  // ---------------------------------------------------------------

  var contentEl    = document.getElementById('content');
  var backBtn      = document.getElementById('navBackBtn');
  var navTitleEl   = document.getElementById('navTitle');
  var navMenuBtn   = document.getElementById('navMenuBtn');
  var navMenuWrap  = document.getElementById('navMenuTrigger');
  var navDropdown  = document.getElementById('navDropdown');
  var fontDecBtn   = document.getElementById('fontDecBtn');
  var fontIncBtn   = document.getElementById('fontIncBtn');

  var WELCOME_HTML = contentEl ? contentEl.innerHTML : '';
  var DEFAULT_TITLE = navTitleEl ? navTitleEl.textContent : 'Presentations';

  // ---------------------------------------------------------------
  // Font-size control — scales #content only, persisted locally
  // ---------------------------------------------------------------

  var FONT_MIN = 8;
  var FONT_MAX = 36;
  var FONT_STEP = 1;
  var FONT_DEFAULT = 16;

  function applyFontSize(px) {
    if (contentEl) contentEl.style.fontSize = px + 'px';
  }

  var fontSize = dbGet('fontSize', FONT_DEFAULT);
  applyFontSize(fontSize);

  if (fontDecBtn) {
    fontDecBtn.addEventListener('click', function () {
      fontSize = Math.max(FONT_MIN, fontSize - FONT_STEP);
      applyFontSize(fontSize);
      dbSet('fontSize', fontSize);
    });
  }

  if (fontIncBtn) {
    fontIncBtn.addEventListener('click', function () {
      fontSize = Math.min(FONT_MAX, fontSize + FONT_STEP);
      applyFontSize(fontSize);
      dbSet('fontSize', fontSize);
    });
  }

  // ---------------------------------------------------------------
  // Nav dropdown menu
  //
  // Desktop:
  //   - Hover opens the menu.
  //   - Leaving the button/dropdown starts a delayed close.
  //
  // Touch / click:
  //   - Tap/click toggles the menu.
  //
  // General:
  //   - Outside click closes immediately.
  //   - Escape closes immediately.
  // ---------------------------------------------------------------

  var menuCloseTimer = null;
  var MENU_CLOSE_DELAY = 2000; // 2 seconds


  function openMenu() {
    clearTimeout(menuCloseTimer);

    if (navMenuWrap) {
      navMenuWrap.classList.add('is-open');
    }

    if (navMenuBtn) {
      navMenuBtn.setAttribute('aria-expanded', 'true');
    }
  }


  function closeMenu() {
    clearTimeout(menuCloseTimer);

    if (navMenuWrap) {
      navMenuWrap.classList.remove('is-open');
    }

    if (navMenuBtn) {
      navMenuBtn.setAttribute('aria-expanded', 'false');
    }
  }


  function scheduleMenuClose() {
    clearTimeout(menuCloseTimer);

    menuCloseTimer = setTimeout(function () {
      closeMenu();
    }, MENU_CLOSE_DELAY);
  }


  function cancelMenuClose() {
    clearTimeout(menuCloseTimer);
    menuCloseTimer = null;
  }


  // ---------------------------------------------------------------
  // Click / tap on menu button
  // ---------------------------------------------------------------

  if (navMenuBtn) {
    navMenuBtn.addEventListener('click', function (e) {
      e.stopPropagation();

      if (navMenuWrap && navMenuWrap.classList.contains('is-open')) {
        closeMenu();
      } else {
        openMenu();
      }
    });
  }


  // ---------------------------------------------------------------
  // Desktop hover
  //
  // Pointer events let this work nicely with mouse/trackpad while
  // not interfering with touch screens.
  // ---------------------------------------------------------------

  if (navMenuWrap) {

    navMenuWrap.addEventListener('pointerenter', function (e) {
      // Only use hover behavior for mouse/trackpad.
      if (e.pointerType === 'mouse') {
        openMenu();
      }
    });

    navMenuWrap.addEventListener('pointerleave', function (e) {
      if (e.pointerType === 'mouse') {
        scheduleMenuClose();
      }
    });

  }


  // ---------------------------------------------------------------
  // Outside click / tap
  // ---------------------------------------------------------------

  document.addEventListener('click', function (e) {
    if (navMenuWrap && !navMenuWrap.contains(e.target)) {
      closeMenu();
    }
  });


  // ---------------------------------------------------------------
  // Escape
  // ---------------------------------------------------------------

  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') {
      closeMenu();
    }
  });


  // ---------------------------------------------------------------
  // Dropdown links
  // ---------------------------------------------------------------

  if (navDropdown) {
    navDropdown.addEventListener('click', function (e) {
      var link = e.target.closest('a[data-slug]');
      if (!link) return;

      e.preventDefault();

      loadTemplate(
        link.getAttribute('data-slug'),
        link.textContent.trim()
      );

      closeMenu();
    });
  }

  // ---------------------------------------------------------------
  // Collapsible headings (accordion)
  //
  // Flat grouping: a heading's "body" is every sibling node that
  // follows it up to (not including) the next heading of ANY level.
  // Heading level (h1-h6) only affects how a section looks — it does
  // not create nesting/parent-child collapse behavior.
  //
  // Must be re-run after every innerHTML swap of #content, since that
  // destroys and recreates every heading/body element.
  // ---------------------------------------------------------------

  var HEADING_TAGS = ['H1', 'H2', 'H3', 'H4', 'H5', 'H6'];

  function isHeading(node) {
    return !!node && HEADING_TAGS.indexOf(node.tagName) !== -1;
  }

  function hasRealContent(el) {
    return Array.prototype.some.call(el.childNodes, function (node) {
      return node.nodeType !== Node.TEXT_NODE || node.textContent.trim() !== '';
    });
  }

  function makeChevron() {
    var chevron = document.createElement('span');
    chevron.className = 'accordion-chevron';
    chevron.setAttribute('aria-hidden', 'true');
    chevron.innerHTML =
      '<svg viewBox="0 0 24 24" width="24" height="24" fill="none" ' +
      'aria-hidden="true" focusable="false">' +
      '<path d="M6 9l6 6 6-6" stroke="currentColor" stroke-width="2" ' +
      'stroke-linecap="round" stroke-linejoin="round"/></svg>';
    return chevron;
  }

  function initAccordions(root) {
    if (!root) return;

    var headings = Array.prototype.filter.call(root.children, isHeading);

    headings.forEach(function (heading) {

      var inner = document.createElement('div');
      inner.className = 'accordion-body-inner';

      var node = heading.nextSibling;
      while (node && !isHeading(node)) {
        var next = node.nextSibling;
        inner.appendChild(node);
        node = next;
      }

      // Heading is immediately followed by another heading (or nothing) —
      // no content to collapse, so leave it as a plain heading.
      if (!hasRealContent(inner)) return;

      heading.classList.add('accordion-toggle');
      heading.setAttribute('role', 'button');
      heading.setAttribute('tabindex', '0');

      // True: headings expanded, False: headings collapsed
      heading.setAttribute('aria-expanded', 'false');
      heading.appendChild(makeChevron());

      var body = document.createElement('div');
      body.className = 'accordion-body is-collapsed';
      body.appendChild(inner);

      heading.insertAdjacentElement('afterend', body);
    });
  }

  function toggleAccordionSection(heading) {
    var body = heading.nextElementSibling;
    if (!body || !body.classList.contains('accordion-body')) return;

    var expanded = heading.getAttribute('aria-expanded') !== 'false';

    heading.setAttribute('aria-expanded', expanded ? 'false' : 'true');
    body.classList.toggle('is-collapsed', expanded);
  }

  if (contentEl) {

    contentEl.addEventListener('click', function (e) {
      var heading = e.target.closest('.accordion-toggle');
      if (!heading) return;
      toggleAccordionSection(heading);
    });

    contentEl.addEventListener('keydown', function (e) {
      if (e.key !== 'Enter' && e.key !== ' ') return;
      var heading = e.target.closest('.accordion-toggle');
      if (!heading) return;
      e.preventDefault();
      toggleAccordionSection(heading);
    });
  }

  // ---------------------------------------------------------------
  // Template loading / back-to-welcome
  // ---------------------------------------------------------------

  function loadTemplate(slug, title) {
    if (!contentEl) return;

    fetch('templates/' + slug + '.html')
      .then(function (r) {
        if (!r.ok) throw new Error('Falló en cargar correctamente ' + slug);
        return r.text();
      })
      .then(function (fragment) {
        contentEl.innerHTML = fragment;
        initAccordions(contentEl);
        contentEl.scrollTop = 0;
        window.scrollTo(0, 0);
        if (navTitleEl) navTitleEl.textContent = title || slug;
        if (backBtn) backBtn.style.display = '';
      })
      .catch(function (err) {
        console.error('[app] loadTemplate failed:', err);
        var msg = isFileProtocol()
          ? 'This site needs to run from a local web server, not be opened directly as a file. Run <code>python -m http.server</code> in this folder, then open <br/><code>http://localhost:8000/</code>.'
          : 'Lo sentimos mucho, pero esa presentación no se pudo abrir correctamente.';
        contentEl.innerHTML = '<p style="padding:20px;">' + msg + '</p>';
        if (navTitleEl) navTitleEl.textContent = title || slug;
        if (backBtn) backBtn.style.display = '';
      });
  }

  function goHome() {
    if (!contentEl) return;
    contentEl.innerHTML = WELCOME_HTML;
    initAccordions(contentEl);
    if (navTitleEl) navTitleEl.textContent = DEFAULT_TITLE;
    if (backBtn) backBtn.style.display = 'none';
    window.scrollTo(0, 0);
    bindWelcomeSearch();
  }

  if (backBtn) backBtn.addEventListener('click', goHome);

  // ---------------------------------------------------------------
  // Search (Fuse-powered, live results from the 3rd character)
  // ---------------------------------------------------------------

  var MIN_QUERY_LENGTH = 3;
  var fuse = null;
  var searchData = [];

  fetch('templates/search-index.json')
    .then(function (r) { return r.json(); })
    .then(function (data) {
      searchData = (data && data.entries) || [];

      if (typeof Fuse === 'undefined') {
        console.error('[app] Fuse is not loaded — search-index.json fetched but search is disabled.');
        return;
      }

      fuse = new Fuse(searchData, {
        includeScore: true,
        includeMatches: true,
        ignoreLocation: true,
        distance: 3600,
        threshold: 0.3,
        minMatchCharLength: 3,
        keys: [
          { name: 'search', weight: 0.6 },
          { name: 'title_norm', weight: 0.4 }
        ]
      });

    })
    .catch(function (err) {
      console.error('[app] Failed to load search-index.json:', err);
      var resultsEl = document.getElementById('searchResults');
      if (resultsEl && isFileProtocol()) {
        resultsEl.innerHTML = '<p class="search-empty">Search needs a local web server — run <code>python -m http.server</code> in this folder, then open http://localhost:8000/.</p>';
      }
    });

  function buildSearchSnippet(result) {
    var entry = result.item || result;
    var matches = result.matches || [];

    // Prefer matches in the main searchable content.
    // Fall back to title_norm if necessary.
    var match = null;

    for (var i = 0; i < matches.length; i++) {
      if (matches[i].key === 'search') {
        match = matches[i];
        break;
      }
    }

    if (!match && matches.length) {
      match = matches[0];
    }

    var text = entry.search || entry.title || '';

    if (!text) return '';

    // No usable match information — show the beginning of the text.
    if (!match || !match.indices || !match.indices.length) {
      var fallbackWords = text.trim().split(/\s+/).slice(0, 7);

      return escapeHtml(fallbackWords.join(' ')) +
        (text.trim().split(/\s+/).length > 7 ? '…' : '');
    }

    /*
     * Fuse gives character ranges as:
     *
     *   [[start, end], [start, end]]
     *
     * We use the first matching range.
     */
    var start = match.indices[0][0];
    var end = match.indices[0][1];

    // Find the beginning of the 3rd word before the match.
    var before = text.slice(0, start);
    var beforeWords = before.trim().split(/\s+/);

    var snippetStart = 0;

    if (beforeWords.length > 3) {
      var wordsToKeep = beforeWords.slice(-3).join(' ');
      snippetStart = before.lastIndexOf(wordsToKeep);
    }

    // Find the end of the 3rd word after the match.
    var after = text.slice(end + 1);
    var afterWords = after.trim().split(/\s+/);

    var snippetEnd = text.length;

    if (afterWords.length > 3) {
      var wordsToKeepAfter = afterWords.slice(0, 3).join(' ');
      var afterStart = after.indexOf(wordsToKeepAfter);

      if (afterStart !== -1) {
        snippetEnd = end + 1 + afterStart + wordsToKeepAfter.length;
      }
    }

    var snippet = text.slice(snippetStart, snippetEnd);

    // Recalculate the match position relative to the snippet.
    var relativeStart = start - snippetStart;
    var relativeEnd = end - snippetStart + 1;

    var highlighted =
      escapeHtml(snippet.slice(0, relativeStart)) +
      '<b>' + escapeHtml(snippet.slice(relativeStart, relativeEnd)) + '</b>' +
      escapeHtml(snippet.slice(relativeEnd));

    // Add ellipsis if we're not showing the beginning/end of the text.
    if (snippetStart > 0) {
      highlighted = '…' + highlighted;
    }

    if (snippetEnd < text.length) {
      highlighted += '…';
    }

    return highlighted;
  }

  function renderSearchResults(results) {
    var resultsEl = document.getElementById('searchResults');
    if (!resultsEl) return;

    if (results.length === 0) {
      resultsEl.innerHTML = '<p class="search-empty">No matches found.</p>';
      return;
    }

    resultsEl.innerHTML = results.map(function (result) {
      var entry = result.item || result;
      var snippet = buildSearchSnippet(result);

      return (
        '<a href="#" class="search-result" data-slug="' + escapeHtml(entry.slug) + '">' +
          '<span class="search-result-title">' + escapeHtml(entry.title) + '</span>' +
          '<span class="search-result-snippet">' + snippet + '</span>' +
        '</a>'
      );
    }).join('');
  }

  function runSearch(query) {
    var resultsEl = document.getElementById('searchResults');
    var defaultImg = document.getElementById('welcomeDefaultImg');
    var q = normalizeQuery(query);

    if (!resultsEl) return;

    if (q.length < MIN_QUERY_LENGTH) {
      resultsEl.innerHTML = '';
      if (defaultImg) defaultImg.style.display = '';
      return;
    }

    if (defaultImg) defaultImg.style.display = 'none';

    if (!fuse) {
      resultsEl.innerHTML = '<p class="search-empty">Loading search index…</p>';
      return;
    }

    var matches = fuse.search(q).slice(0, 20);

    renderSearchResults(matches);
  }

  var debouncedSearch = debounce(function (val) { runSearch(val); }, 150);

  function bindWelcomeSearch() {
    var input = document.getElementById('searchInput');
    var clearBtn = document.getElementById('searchClearBtn');
    var resultsEl = document.getElementById('searchResults');

    if (!input) return;

    input.addEventListener('input', function (e) {
      var val = e.target.value;
      if (clearBtn) clearBtn.style.display = val.length ? '' : 'none';
      debouncedSearch(val);
    });

    if (clearBtn) {
      clearBtn.addEventListener('click', function () {
        input.value = '';
        clearBtn.style.display = 'none';
        runSearch('');
        input.focus();
      });
    }

    if (resultsEl) {
      resultsEl.addEventListener('click', function (e) {
        var link = e.target.closest('a[data-slug]');
        if (!link) return;
        e.preventDefault();
        var slug = link.getAttribute('data-slug');
        var entry = null;
        for (var i = 0; i < searchData.length; i++) {
          if (searchData[i].slug === slug) { entry = searchData[i]; break; }
        }
        loadTemplate(slug, entry ? entry.title : slug);
      });
    }
  }

  bindWelcomeSearch();
})();
