/**
 * js/app.js
 * Auto-generated by generate_site.py — edits here are overwritten on the
 * next run. Edit JS_APP_TEMPLATE in generate_site.py instead.
 *
 * Drives:
 *   - the always-visible nav (back button, template menu, font-size buttons)
 *   - fetching + injecting template/<slug>.html into #content
 *   - the welcome view’s Fuse-powered search (live from the 3ʳᵈ character)
 */

(function () {
  'use strict';

  // ---------------------------------------------------------------
  // Small helpers
  // ---------------------------------------------------------------

  var STORAGE_PREFIX = 'Presentaciones:';

  function dbGet(key, fallback) {
    try {
      var raw = localStorage.getItem(STORAGE_PREFIX + key);
      return raw === null ? fallback : JSON.parse(raw);
    } catch (e) {
      return fallback;
    }
  }

  function dbSet(key, value) {
    try {
      localStorage.setItem(STORAGE_PREFIX + key, JSON.stringify(value));
    } catch (e) {
      /* ignore quota / privacy-mode errors */
    }
  }

  function escapeHtml(str) {
    var p = document.createElement('p');
    p.textContent = str == null ? '' : String(str);
    return p.innerHTML;
  }

  function debounce(fn, wait) {
    var timer;
    return function () {
      var args = arguments;
      clearTimeout(timer);
      timer = setTimeout(function () { fn.apply(null, args); }, wait);
    };
  }

  /* Mirrors the Python-side normalize_search_text() so indexed text and
     typed queries normalize the same way. */
  function normalizeQuery(str) {
    return String(str || '')
      .toLowerCase()
      .normalize('NFD')
      .replace(/[̀-ͯ]/g, '')
      .replace(/[^a-z0-9\s]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function isFileProtocol() {
    return location.protocol === 'file:';
  }

  // ---------------------------------------------------------------
  // Persistent DOM refs (these nodes are never replaced — only
  // #content's innerHTML changes, so anything inside #content must be
  // re-queried after each swap instead of cached up here)
  // ---------------------------------------------------------------

  var contentEl    = document.getElementById('content');
  var backBtn      = document.getElementById('navBackBtn');
  var navTitleEl   = document.getElementById('navTitle');
  var navMenuBtn   = document.getElementById('navMenuBtn');
  var navMenuWrap  = document.getElementById('navMenuTrigger');
  var navDropdown  = document.getElementById('navDropdown');
  var fontDecBtn   = document.getElementById('fontDecBtn');
  var fontIncBtn   = document.getElementById('fontIncBtn');

  var WELCOME_HTML = contentEl ? contentEl.innerHTML : '';
  var DEFAULT_TITLE = navTitleEl ? navTitleEl.textContent : 'Presentaciones';

  // ---------------------------------------------------------------
  // Font-size control — scales #content only, persisted locally
  // ---------------------------------------------------------------

  var FONT_MIN = 8;
  var FONT_MAX = 36;
  var FONT_STEP = 1;
  var FONT_DEFAULT = 16;

  function applyFontSize(px) {
    if (contentEl) contentEl.style.fontSize = px + 'px';
  }

  var fontSize = dbGet('fontSize', FONT_DEFAULT);
  applyFontSize(fontSize);

  if (fontDecBtn) {
    fontDecBtn.addEventListener('click', function () {
      fontSize = Math.max(FONT_MIN, fontSize - FONT_STEP);
      applyFontSize(fontSize);
      dbSet('fontSize', fontSize);
    });
  }

  if (fontIncBtn) {
    fontIncBtn.addEventListener('click', function () {
      fontSize = Math.min(FONT_MAX, fontSize + FONT_STEP);
      applyFontSize(fontSize);
      dbSet('fontSize', fontSize);
    });
  }

  // ---------------------------------------------------------------
  // Nav dropdown menu
  //
  // Desktop:
  //   - Hover opens the menu.
  //   - Leaving the button/dropdown starts a delayed close.
  //
  // Touch / click:
  //   - Tap/click toggles the menu.
  //
  // General:
  //   - Outside click closes immediately.
  //   - Escape closes immediately.
  // ---------------------------------------------------------------

  var menuCloseTimer = null;
  var MENU_CLOSE_DELAY = 2300; // 2.3 seconds


  function openMenu() {
    clearTimeout(menuCloseTimer);

    if (navMenuWrap) {
      navMenuWrap.classList.add('is-open');
    }

    if (navMenuBtn) {
      navMenuBtn.setAttribute('aria-expanded', 'true');
    }
  }


  function closeMenu() {
    clearTimeout(menuCloseTimer);

    if (navMenuWrap) {
      navMenuWrap.classList.remove('is-open');
    }

    if (navMenuBtn) {
      navMenuBtn.setAttribute('aria-expanded', 'false');
    }
  }


  function scheduleMenuClose() {
    clearTimeout(menuCloseTimer);

    menuCloseTimer = setTimeout(function () {
      closeMenu();
    }, MENU_CLOSE_DELAY);
  }


  function cancelMenuClose() {
    clearTimeout(menuCloseTimer);
    menuCloseTimer = null;
  }


  // ---------------------------------------------------------------
  // Click / tap on menu button
  // ---------------------------------------------------------------

  if (navMenuBtn) {
    navMenuBtn.addEventListener('click', function (e) {
      e.stopPropagation();

      if (navMenuWrap && navMenuWrap.classList.contains('is-open')) {
        closeMenu();
      } else {
        openMenu();
      }
    });
  }


  // ---------------------------------------------------------------
  // Desktop hover
  //
  // Pointer events let this work nicely with mouse/trackpad while
  // not interfering with touch screens.
  // ---------------------------------------------------------------

  if (navMenuWrap) {

    navMenuWrap.addEventListener('pointerenter', function (e) {
      // Only use hover behavior for mouse/trackpad.
      if (e.pointerType === 'mouse') {
        openMenu();
      }
    });

    navMenuWrap.addEventListener('pointerleave', function (e) {
      if (e.pointerType === 'mouse') {
        scheduleMenuClose();
      }
    });

  }


  // ---------------------------------------------------------------
  // Outside click / tap
  // ---------------------------------------------------------------

  document.addEventListener('click', function (e) {
    if (navMenuWrap && !navMenuWrap.contains(e.target)) {
      closeMenu();
    }
  });


  // ---------------------------------------------------------------
  // Escape
  // ---------------------------------------------------------------

  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') {
      closeMenu();
    }
  });


  // ---------------------------------------------------------------
  // Dropdown links
  // ---------------------------------------------------------------

  if (navDropdown) {
    navDropdown.addEventListener('click', function (e) {
      var link = e.target.closest('a[data-slug]');
      if (!link) return;

      e.preventDefault();

      openedFromSearch = false;
      loadTemplate(
        link.getAttribute('data-slug'),
        link.textContent.trim()
      );

      closeMenu();
    });
  }

  // ---------------------------------------------------------------
  // Collapsible headings (accordion)
  //
  // Flat grouping: a heading's "body" is every sibling node that
  // follows it up to (not including) the next heading of ANY level.
  // Heading level (h1-h6) only affects how a section looks — it does
  // not create nesting/parent-child collapse behavior.
  //
  // Must be re-run after every innerHTML swap of #content, since that
  // destroys and recreates every heading/body element.
  // ---------------------------------------------------------------

  var HEADING_TAGS = ['H1', 'H2', 'H3', 'H4', 'H5', 'H6'];

  function isHeading(node) {
    return !!node && HEADING_TAGS.indexOf(node.tagName) !== -1;
  }

  function hasRealContent(el) {
    return Array.prototype.some.call(el.childNodes, function (node) {
      return node.nodeType !== Node.TEXT_NODE || node.textContent.trim() !== '';
    });
  }

  function makeChevron() {
    var chevron = document.createElement('span');
    chevron.className = 'accordion-chevron';
    chevron.setAttribute('aria-hidden', 'true');

    chevron.innerHTML =
      '<svg viewBox="0 0 24 24" width="24" height="24" fill="none" ' +
      'aria-hidden="true" focusable="false">' +
        '<circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="1.5"/>' +
        '<path d="M8 10l4 4 4-4" stroke="currentColor" stroke-width="2" ' +
        'stroke-linecap="round" stroke-linejoin="round"/>' +
      '</svg>';

    return chevron;
  }

  function initAccordions(root) {
    if (!root) return;

    var headings = Array.prototype.filter.call(root.children, isHeading);
    var isFirstToggle = true; // only the first *real* section starts open

    headings.forEach(function (heading) {

      var inner = document.createElement('div');
      inner.className = 'accordion-body-inner';

      var node = heading.nextSibling;
      while (node && !isHeading(node)) {
        var next = node.nextSibling;
        inner.appendChild(node);
        node = next;
      }

      // Heading is immediately followed by another heading (or nothing) —
      // no content to collapse, so leave it as a plain heading.
      if (!hasRealContent(inner)) return;

      heading.classList.add('accordion-toggle');
      heading.setAttribute('role', 'button');
      heading.setAttribute('tabindex', '0');

      var startExpanded = isFirstToggle;
      isFirstToggle = false;

      heading.setAttribute('aria-expanded', startExpanded ? 'true' : 'false');
      heading.appendChild(makeChevron());

      var body = document.createElement('div');
      body.className = 'accordion-body' + (startExpanded ? '' : ' is-collapsed');
      body.appendChild(inner);

      heading.insertAdjacentElement('afterend', body);
    });
  }

  function toggleAccordionSection(heading) {
    var body = heading.nextElementSibling;
    if (!body || !body.classList.contains('accordion-body')) return;

    var expanded = heading.getAttribute('aria-expanded') !== 'false';

    heading.setAttribute('aria-expanded', expanded ? 'false' : 'true');
    body.classList.toggle('is-collapsed', expanded);
  }

  function toggleAllAccordions(root) {
    if (!root) return;

    var headings = Array.prototype.filter.call(root.children, isHeading)
      .filter(function (h) { return h.classList.contains('accordion-toggle'); });

    if (!headings.length) return;

    // If any section is currently collapsed, expand everything;
    // otherwise collapse everything.
    var anyCollapsed = headings.some(function (h) {
      return h.getAttribute('aria-expanded') === 'false';
    });

    headings.forEach(function (heading) {
      var body = heading.nextElementSibling;
      if (!body || !body.classList.contains('accordion-body')) return;
      heading.setAttribute('aria-expanded', anyCollapsed ? 'true' : 'false');
      body.classList.toggle('is-collapsed', !anyCollapsed);
    });
  }

  var accordionClickTimer = null;
  var ACCORDION_CLICK_DELAY = 250; // ms — long enough to catch a dblclick

  if (contentEl) {

    contentEl.addEventListener('click', function (e) {
      var heading = e.target.closest('.accordion-toggle');
      if (!heading) return;

      // Delay the single-tap toggle so a fast second tap (dblclick)
      // can cancel it and run "toggle all" instead.
      clearTimeout(accordionClickTimer);
      accordionClickTimer = setTimeout(function () {
        toggleAccordionSection(heading);
      }, ACCORDION_CLICK_DELAY);
    });

    contentEl.addEventListener('dblclick', function (e) {
      clearTimeout(accordionClickTimer);
      e.preventDefault();
      toggleAllAccordions(contentEl);
    });

    contentEl.addEventListener('keydown', function (e) {
      if (e.key !== 'Enter' && e.key !== ' ') return;
      var heading = e.target.closest('.accordion-toggle');
      if (!heading) return;
      e.preventDefault();
      toggleAccordionSection(heading);
    });

    // OPEN button inside a search-result group. Bound once here (rather
    // than re-bound in bindWelcomeSearch) since #content's innerHTML gets
    // replaced wholesale on every nav, but the #content node itself never
    // does.
    contentEl.addEventListener('click', function (e) {
      var openBtn = e.target.closest('.search-group-open-btn');
      if (!openBtn) return;
      e.preventDefault();

      var slug = openBtn.getAttribute('data-slug');
      var entry = null;
      for (var i = 0; i < searchData.length; i++) {
        if (searchData[i].slug === slug) { entry = searchData[i]; break; }
      }

      openedFromSearch = true;
      loadTemplate(slug, entry ? entry.title : slug);
    });
  }

  var CONTENT_TRANSITION_MS = 300; // keep in sync with #content's CSS transition duration

  function swapContentWithTransition(applyFn) {
    if (!contentEl) { applyFn(); return; }

    contentEl.classList.add('content-notransition', 'content-offscreen-right');
    applyFn();
    void contentEl.offsetWidth; // flush layout so the snap-to-offscreen commits instantly

    contentEl.classList.remove('content-notransition');

    requestAnimationFrame(function () {
      contentEl.classList.remove('content-offscreen-right');
    });
  }

  function exitContentThen(afterExit) {
    if (!contentEl) { afterExit(); return; }

    var done = false;
    function finish(e) {
      if (e && e.target !== contentEl) return;
      if (done) return;
      done = true;
      contentEl.removeEventListener('transitionend', finish);
      afterExit();
    }

    contentEl.addEventListener('transitionend', finish);
    // Fallback in case transitionend never fires (prefers-reduced-motion,
    // a backgrounded tab throttling timers, etc.)
    setTimeout(finish, CONTENT_TRANSITION_MS + 50);

    contentEl.classList.add('content-offscreen-right');
  }

  // ---------------------------------------------------------------
  // Template loading / back-to-welcome
  // ---------------------------------------------------------------

  function loadTemplate(slug, title) {
    if (!contentEl) return;
    stopSlideshow();
    teardownResultsObserver();
    document.documentElement.classList.add('is-template-view');

    fetch('templates/' + slug + '.html')
      .then(function (r) {
        if (!r.ok) throw new Error('Falló en cargar correctamente ' + slug);
        return r.text();
      })
      .then(function (fragment) {
        swapContentWithTransition(function () {
          contentEl.innerHTML = fragment;
          initAccordions(contentEl);
          contentEl.scrollTop = 0;
          window.scrollTo(0, 0);
          if (navTitleEl) navTitleEl.textContent = title || slug;
          if (backBtn) backBtn.style.display = '';
          initFooterMarquee();
        });
      })
      .catch(function (err) {
        console.error('[app] loadTemplate failed:', err);
        var msg = isFileProtocol()
          ? 'Este sitio debe ejecutarse desde un servidor web local, no abrirse directamente como un archivo. Ejecuta <code>python -m http.server</code> en esta carpeta y, luego, abre <br/><b><code>http://localhost:8000/</code></b>.'
          : 'Lo sentimos mucho, pero esa presentación no se pudo abrir correctamente.';
        swapContentWithTransition(function () {
          contentEl.innerHTML = '<p style="padding:20px;">' + msg + '</p>';
          if (navTitleEl) navTitleEl.textContent = title || slug;
          if (backBtn) backBtn.style.display = '';
        });
      });
  }

  function goHome() {
    if (!contentEl) return;

    exitContentThen(function () {
      teardownResultsObserver();
      openedFromSearch = false;
      stopFooterMarquee();
      document.documentElement.classList.remove('is-template-view');

      swapContentWithTransition(function () {
        contentEl.innerHTML = WELCOME_HTML;
        initAccordions(contentEl);
        if (navTitleEl) navTitleEl.textContent = DEFAULT_TITLE;
        if (backBtn) backBtn.style.display = 'none';
        window.scrollTo(0, 0);
        bindWelcomeSearch();
        initSlideshow();
      });
    });
  }

  if (backBtn) {
    backBtn.addEventListener('click', function () {
      if (openedFromSearch) {
        backToSearchResults();
      } else {
        goHome();
      }
    });
  }

  // ---------------------------------------------------------------
  // Footer marquee (template-view ticker)
  //
  // .footer-template-text / .footer-home-text visibility is CSS-only,
  // driven entirely by html.is-template-view — this only measures
  // whether the single (first) copy of the ticker text overflows its
  // container, and if so turns on the seamless duplicate-span loop.
  // Re-run every time a template loads, since title length varies.
  // ---------------------------------------------------------------

  function initFooterMarquee() {
    var container = document.querySelector('.footer-template-text');
    var track = document.querySelector('.footer-marquee-track');
    var firstSpan = track && track.querySelector('span');

    if (!container || !track || !firstSpan) return;

    track.classList.remove('marquee');
    track.style.removeProperty('--marquee-duration');

    requestAnimationFrame(function () {
      var overflow = firstSpan.scrollWidth - container.clientWidth;

      if (overflow > 0) {
        var duration = Math.max(15, Math.min(60, firstSpan.scrollWidth / 40));
        track.style.setProperty('--marquee-duration', duration + 's');
        track.classList.add('marquee');
      }
    });
  }

  function stopFooterMarquee() {
    var track = document.querySelector('.footer-marquee-track');
    if (!track) return;
    track.classList.remove('marquee');
    track.style.removeProperty('--marquee-duration');
  }

  // ---------------------------------------------------------------
  // Welcome-view slideshow
  //
  // Cycles #welcomeDefaultImg through a hardcoded list of images.
  // Each slide's caption comes from its `alt`: text before the first
  // "|" is the title, text after is the body; with no "|" the whole
  // alt is shown as the title only.
  // ---------------------------------------------------------------

  var SLIDES = [
    {
      src: 'img/rk_purva-raga.jpg',
      alt: 'Pūrva-raga | Śrīmatī Rādhikā se arregla para encontrarse con Kṛṣṇa.'
    },
    {
      src: 'img/rk_bhojan-lila-on-yamuna.jpg',
      alt: 'Śrī Śrī Rādhā Kṛṣṇa | Śrīmatī Rādhārāṇī da de comer a Kṛṣṇa.'
    },
    {
      src: 'img/rk_nikunj-rasa.jpg',
      alt: 'Nikuñja Rāsa | Las sakhīs adoran Śrī Śrī Rādhā Kṛṣṇa.'
    },
    {
      src: 'img/rk_vina.jpg',
      alt: 'Śrī Śrī Rādhā Kṛṣṇa | tocando la vina (instrumento de cuerdas).'
    }
    // Optional per-slide `position` (e.g. 'top center') controls both
    // object-position and the Ken Burns zoom origin; defaults to 'center'.
  ];

  var SLIDE_DURATION_MS = 9200; // how long each slide stays on screen
  var slideTimer = null;

  // Parses "Título | Texto" into {heading, body}; with no "|" the whole
  // string becomes a title-only caption.
  function parseSlideCaption(alt) {
    var raw = (alt || '').trim();
    if (!raw) return null;

    var pipeIdx = raw.indexOf('|');
    if (pipeIdx === -1) return { heading: raw, body: '' };

    var heading = raw.slice(0, pipeIdx).trim();
    var body = raw.slice(pipeIdx + 1).trim();
    if (!heading && !body) return null;
    return { heading: heading, body: body };
  }

  function initSlideshow() {
    var wrapper = document.querySelector('#welcomeDefaultImg .ken-burns-frame');
    var layerA = wrapper && wrapper.querySelector('.slide-a');
    var layerB = wrapper && wrapper.querySelector('.slide-b');

    if (!wrapper || !layerA || !layerB || !SLIDES.length) return;

    stopSlideshow();

    // Block the native right-click / long-press context menu (its "open
    // image in new tab" is the thing that breaks the app-like feel).
    // Doesn't stop someone from downloading the image some other way —
    // just removes that one easy exit out of the page.
    wrapper.addEventListener('contextmenu', function (e) {
      e.preventDefault();
    });

    var i = 0;
    var front = layerA;
    var back = layerB;

    function setSlide(layer, item) {
      var img = layer.querySelector('.slideshow');
      var captionEl = layer.querySelector('.slide-caption');
      var headingEl = layer.querySelector('.slide-caption-heading');
      var bodyEl = layer.querySelector('.slide-caption-body');

      img.src = item.src;
      img.alt = item.alt || '';
      img.style.objectPosition = item.position || 'center';
      img.style.setProperty('--kb-origin', item.position || 'center');

      // Restart the Ken Burns animation cleanly on this layer.
      img.style.animation = 'none';
      void img.offsetWidth; // force reflow
      img.style.animation = '';

      var parsed = parseSlideCaption(item.alt);
      if (parsed) {
        headingEl.textContent = parsed.heading;
        bodyEl.textContent = parsed.body;
        captionEl.classList.remove('slide-caption-empty');
      } else {
        headingEl.textContent = '';
        bodyEl.textContent = '';
        captionEl.classList.add('slide-caption-empty');
      }
    }

    function preloadNext(idx) {
      var pre = new Image();
      pre.src = SLIDES[(idx + 1) % SLIDES.length].src;
    }

    setSlide(front, SLIDES[i]);
    front.classList.add('slide-visible');
    preloadNext(i);

    if (SLIDES.length < 2) return; // nothing to cycle to

    slideTimer = setInterval(function () {
      i = (i + 1) % SLIDES.length;
      setSlide(back, SLIDES[i]);
      back.classList.add('slide-visible');
      front.classList.remove('slide-visible');
      var tmp = front; front = back; back = tmp;
      preloadNext(i);
    }, SLIDE_DURATION_MS);
  }

  function stopSlideshow() {
    clearInterval(slideTimer);
    slideTimer = null;
  }

  // ---------------------------------------------------------------
  // Search (Fuse-powered, live results from the 3rd character)
  // ---------------------------------------------------------------

  var MIN_QUERY_LENGTH = 3;
  var BATCH_SIZE = 10;
  var MAX_BULLETS = 7;

  var fuseTitle = null;   // Tier 1: fuzzy match on title_norm only
  var fuseContent = null; // Tier 3: fuzzy match on search (body) only
  var searchData = [];

  var currentResults = [];  // full ranked group list for the active query
  var renderedCount = 0;    // how many groups have been appended so far
  var lastQuery = '';       // raw (un-normalized) text of the last run search
  var openedFromSearch = false; // true if the open template came from a search result
  var resultsObserver = null;   // IntersectionObserver driving lazy-load

  fetch('templates/search-index.json')
    .then(function (r) { return r.json(); })
    .then(function (data) {
      searchData = (data && data.entries) || [];

      if (typeof Fuse === 'undefined') {
        console.error('[app] El fuse.min.js no cargó: se ha obtenido el archivo search-index.json, pero la búsqueda está desactivada.');
        return;
      }

      var fuseSharedOptions = {
        ignoreLocation: true,
        distance: 3600,
        threshold: 0.3,
        minMatchCharLength: 3
      };

      fuseTitle = new Fuse(searchData, {
        ignoreLocation: fuseSharedOptions.ignoreLocation,
        distance: fuseSharedOptions.distance,
        threshold: fuseSharedOptions.threshold,
        minMatchCharLength: fuseSharedOptions.minMatchCharLength,
        keys: ['title_norm']
      });

      fuseContent = new Fuse(searchData, {
        ignoreLocation: fuseSharedOptions.ignoreLocation,
        distance: fuseSharedOptions.distance,
        threshold: fuseSharedOptions.threshold,
        minMatchCharLength: fuseSharedOptions.minMatchCharLength,
        keys: ['search']
      });

    })
    .catch(function (err) {
      console.error('[app] No se pudo cargar el search-index.json:', err);
      var resultsEl = document.getElementById('searchResults');
      if (resultsEl && isFileProtocol()) {
        resultsEl.innerHTML = '<p class="search-empty">Search necesita un servidor web local: ejecuta <code>python -m http.server</code> en esta carpeta y, luego, abre: http://localhost:8000/.</p>';
      }
    });

  // Builds a "…3 words <b>match</b> 3 words…" snippet around an arbitrary
  // [start, end) character range in `text` (end is exclusive). Generalized
  // from the old fuse-match-only version so any literal occurrence can use it.
  function snippetAroundMatch(text, start, end) {
    var before = text.slice(0, start);
    var beforeWords = before.trim().split(/\s+/);

    var snippetStart = 0;

    if (beforeWords.length > 3) {
      var wordsToKeep = beforeWords.slice(-3).join(' ');
      snippetStart = before.lastIndexOf(wordsToKeep);
    }

    var after = text.slice(end);
    var afterWords = after.trim().split(/\s+/);

    var snippetEnd = text.length;

    if (afterWords.length > 3) {
      var wordsToKeepAfter = afterWords.slice(0, 3).join(' ');
      var afterStart = after.indexOf(wordsToKeepAfter);

      if (afterStart !== -1) {
        snippetEnd = end + afterStart + wordsToKeepAfter.length;
      }
    }

    var snippet = text.slice(snippetStart, snippetEnd);

    var relativeStart = start - snippetStart;
    var relativeEnd = end - snippetStart;

    var highlighted =
      escapeHtml(snippet.slice(0, relativeStart)) +
      '<b>' + escapeHtml(snippet.slice(relativeStart, relativeEnd)) + '</b>' +
      escapeHtml(snippet.slice(relativeEnd));

    if (snippetStart > 0) {
      highlighted = '…' + highlighted;
    }

    if (snippetEnd < text.length) {
      highlighted += '…';
    }

    return highlighted;
  }

  // Repeated indexOf — every literal, non-overlapping occurrence of
  // `needle` in `haystack`, capped at `maxCount`.
  function findLiteralOccurrences(haystack, needle, maxCount) {
    var occurrences = [];
    if (!needle) return occurrences;

    var idx = haystack.indexOf(needle);
    while (idx !== -1 && occurrences.length < maxCount) {
      occurrences.push({ start: idx, end: idx + needle.length });
      idx = haystack.indexOf(needle, idx + needle.length);
    }
    return occurrences;
  }

  // Total count of literal occurrences (uncapped) — used only to rank
  // tier-2 (exact content match) results by relevance.
  function countOccurrences(haystack, needle) {
    if (!needle) return 0;
    var count = 0;
    var idx = haystack.indexOf(needle);
    while (idx !== -1) {
      count++;
      idx = haystack.indexOf(needle, idx + needle.length);
    }
    return count;
  }

  // Up to MAX_BULLETS highlighted snippets, one per literal occurrence of
  // the normalized query inside entry.search.
  function buildBulletpoints(entry, normalizedQuery) {
    var text = entry.search || '';
    var occurrences = findLiteralOccurrences(text, normalizedQuery, MAX_BULLETS);

    return occurrences.map(function (occ) {
      return snippetAroundMatch(text, occ.start, occ.end);
    });
  }

  // ---- Three-tier fallback: title-fuzzy -> content-exact -> content-fuzzy ----

  function buildGroups(rawQuery, normalizedQuery) {
    var groups;

    // Tier 1 — title, fuzzy.
    if (fuseTitle) {
      var titleHits = fuseTitle.search(normalizedQuery);
      if (titleHits.length) {
        groups = titleHits.map(function (hit) {
          var entry = hit.item;
          var bullets = buildBulletpoints(entry, normalizedQuery);
          return {
            entry: entry,
            bulletpoints: bullets,
            note: bullets.length === 0
              ? 'Only the title of this document matches your query "' + rawQuery + '"'
              : null
          };
        });
        return groups;
      }
    }

    // Tier 2 — content, exact substring match across every document.
    var exactHits = [];
    for (var i = 0; i < searchData.length; i++) {
      var entry = searchData[i];
      var text = entry.search || '';
      var count = countOccurrences(text, normalizedQuery);
      if (count > 0) exactHits.push({ entry: entry, count: count });
    }

    if (exactHits.length) {
      exactHits.sort(function (a, b) { return b.count - a.count; });
      groups = exactHits.map(function (hit) {
        return {
          entry: hit.entry,
          bulletpoints: buildBulletpoints(hit.entry, normalizedQuery),
          note: null
        };
      });
      return groups;
    }

    // Tier 3 — content, fuzzy (low-confidence fallback). By construction
    // every result here has zero literal occurrences (tier 2 found none),
    // so bulletpoints will always come back empty — the note is what
    // explains why the document is showing up at all.
    if (!fuseContent) return [];

    var fuzzyHits = fuseContent.search(normalizedQuery);
    groups = fuzzyHits.map(function (hit) {
      var entry = hit.item;
      return {
        entry: entry,
        bulletpoints: buildBulletpoints(entry, normalizedQuery),
        note: 'Este documento podría contener lo que buscas'
      };
    });
    return groups;
  }

  function buildGroupEl(group, shadeClass) {
    var entry = group.entry;

    var wrap = document.createElement('div');
    wrap.className = 'search-group ' + shadeClass;

    var top = document.createElement('div');
    top.className = 'search-group-top';

    var title = document.createElement('h6');
    title.className = 'search-group-title';
    title.textContent = entry.title;

    var openBtn = document.createElement('button');
    openBtn.type = 'button';
    openBtn.className = 'search-group-open-btn';
    openBtn.setAttribute('data-slug', entry.slug);
    openBtn.innerHTML =
      ' ABRIR <span class="open-chevron" aria-hidden="true">' +
        '<svg viewBox="0 0 24 24" width="20" height="20" fill="none">' +
          '<path d="M8 5l7 7-7 7" ' +
            'stroke="currentColor" ' +
            'stroke-width="2.5" ' +
            'stroke-linecap="round" ' +
            'stroke-linejoin="round"/>' +
        '</svg>' +
      '</span>';

    top.appendChild(title);
    top.appendChild(openBtn);
    wrap.appendChild(top);

    if (group.bulletpoints.length) {
      var list = document.createElement('ul');
      list.className = 'search-group-bullets';
      group.bulletpoints.forEach(function (html) {
        var li = document.createElement('li');
        li.innerHTML = html;
        list.appendChild(li);
      });
      wrap.appendChild(list);
    }

    if (group.note) {
      var note = document.createElement('p');
      note.className = 'search-group-note';
      note.textContent = group.note;
      wrap.appendChild(note);
    }

    return wrap;
  }

  // ---- Lazy/batched rendering ----

  function renderNextBatch() {
    var resultsEl = document.getElementById('searchResults');
    if (!resultsEl) return;

    var next = currentResults.slice(renderedCount, renderedCount + BATCH_SIZE);
    if (!next.length) return;

    var frag = document.createDocumentFragment();

    next.forEach(function (group, i) {
      var shadeClass = (renderedCount + i) % 2 === 0 ? 'shade-a' : 'shade-b';
      frag.appendChild(buildGroupEl(group, shadeClass));
    });

    resultsEl.appendChild(frag);
    renderedCount += next.length;
  }

  function teardownResultsObserver() {
    if (resultsObserver) {
      resultsObserver.disconnect();
      resultsObserver = null;
    }
    var oldSentinel = document.getElementById('searchSentinel');
    if (oldSentinel && oldSentinel.parentNode) {
      oldSentinel.parentNode.removeChild(oldSentinel);
    }
  }

  function setupResultsObserver() {
    var resultsEl = document.getElementById('searchResults');
    if (!resultsEl || typeof IntersectionObserver === 'undefined') return;

    var sentinel = document.createElement('div');
    sentinel.id = 'searchSentinel';
    sentinel.className = 'search-sentinel';
    sentinel.setAttribute('aria-hidden', 'true');
    resultsEl.appendChild(sentinel);

    resultsObserver = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) {
        if (!e.isIntersecting) return;
        if (renderedCount >= currentResults.length) {
          teardownResultsObserver();
          return;
        }
        renderNextBatch();
        resultsEl.appendChild(sentinel); // keep sentinel below the new batch
        if (renderedCount >= currentResults.length) {
          teardownResultsObserver();
        }
      });
    }, { root: null, rootMargin: '600px 0px' });

    resultsObserver.observe(sentinel);
  }

  function runSearch(query) {
    var resultsEl = document.getElementById('searchResults');
    var defaultImg = document.getElementById('welcomeDefaultImg');

    if (!resultsEl) return;

    lastQuery = query;

    var q = normalizeQuery(query);

    teardownResultsObserver();
    resultsEl.innerHTML = '';
    currentResults = [];
    renderedCount = 0;

    if (q.length < MIN_QUERY_LENGTH) {
      if (defaultImg) defaultImg.style.display = '';
      return;
    }

    if (defaultImg) defaultImg.style.display = 'none';

    if (!fuseTitle || !fuseContent) {
      resultsEl.innerHTML = '<p class="search-empty">Cargando el índice de búsqueda...</p>';
      return;
    }

    currentResults = buildGroups(query, q);

    if (!currentResults.length) {
      resultsEl.innerHTML = '<p class="search-empty">No se encontraron resultados.</p>';
      return;
    }

    renderNextBatch();
    setupResultsObserver();
  }

  // Restores the welcome view and re-runs the last query, instead of going
  // fully home — used when the back button is pressed after opening a
  // template from a search result.
  function backToSearchResults() {
    if (!contentEl) return;

    exitContentThen(function () {
      stopFooterMarquee();
      document.documentElement.classList.remove('is-template-view');

      swapContentWithTransition(function () {
        contentEl.innerHTML = WELCOME_HTML;
        initAccordions(contentEl);
        if (navTitleEl) navTitleEl.textContent = DEFAULT_TITLE;
        if (backBtn) backBtn.style.display = 'none';
        window.scrollTo(0, 0);
        bindWelcomeSearch();
        initSlideshow();
      });

      var input = document.getElementById('searchInput');
      var clearBtn = document.getElementById('searchClearBtn');
      if (input) input.value = lastQuery;
      if (clearBtn) clearBtn.style.display = lastQuery.length ? '' : 'none';

      openedFromSearch = false;
      runSearch(lastQuery);
    });
  }

  var debouncedSearch = debounce(function (val) { runSearch(val); }, 150);

  function bindWelcomeSearch() {
    var input = document.getElementById('searchInput');
    var clearBtn = document.getElementById('searchClearBtn');

    if (!input) return;

    input.addEventListener('input', function (e) {
      var val = e.target.value;
      if (clearBtn) clearBtn.style.display = val.length ? '' : 'none';
      debouncedSearch(val);
    });

    if (clearBtn) {
      clearBtn.addEventListener('click', function () {
        input.value = '';
        clearBtn.style.display = 'none';
        runSearch('');
        input.focus();
      });
    }
  }

  bindWelcomeSearch();
  initSlideshow();

  // Same enter transition as every navigation, so first paint and every
  // subsequent template open/close feel like one consistent system.
  swapContentWithTransition(function () {});
})();
