/**
 * js/router.js
 * Auto-generated by generate_site.py — edits here are overwritten on the
 * next run. Edit ROUTER_JS_TEMPLATE in generate_site.py instead.
 *
 * Minimal hash router. The URL fragment (e.g. #janmastami) is the single
 * source of truth for "what template is open" — the welcome view is the
 * empty-hash state ("/"). This file only reads/writes location.hash and
 * notifies one registered callback whenever the route changes; it knows
 * nothing about #content, fetch(), or any other app.js internals.
 *
 * Two ways to change the route, with different history semantics:
 *
 *   navigateTo(slug) — normal template-to-template navigation. Pushes a
 *   real history entry (the default behavior of assigning
 *   location.hash), so the browser’s native Back/Forward buttons walk
 *   through the literal sequence of views the user visited, one step
 *   at a time (D -> C -> B -> A -> Welcome).
 *
 *   goHome() — what the app’s OWN visible "Inicio" button means: return
 *   to Welcome in a single step, no matter how many templates deep the
 *   user currently is (D -> [Inicio] -> Welcome directly, NOT
 *   D -> C -> B -> A -> Welcome). This deliberately does not replay
 *   history.back() the right number of times — that would require
 *   tracking depth, could flash through every intermediate template,
 *   and risks walking the user past the app’s own history entirely. It
 *   just clears the hash, which still only pushes ONE new entry — so
 *   the native Back button continues to reflect the real, literal
 *   history afterwards.
 */
(function () {
  'use strict';

  function getCurrentSlug() {
    var raw = location.hash || '';
    raw = raw.replace(/^#/, '');
    return raw ? decodeURIComponent(raw) : '';
  }

  var routeCallback = null;

  function dispatch() {
    if (routeCallback) routeCallback(getCurrentSlug());
  }

  window.addEventListener('hashchange', dispatch);

  window.Router = {

    getCurrentSlug: getCurrentSlug,

    /**
     * Registers the single function that runs whenever the route
     * changes — via a template link, the browser’s native Back/
     * Forward buttons, or navigateTo()/goHome() below. Also invoked
     * once immediately with whatever hash the page loaded with, so a
     * hard refresh on #some-slug renders that template directly
     * instead of the welcome view.
     */
    onRouteChange: function (callback) {
      routeCallback = callback;
      dispatch();
    },

    navigateTo: function (slug) {
      location.hash = slug;
    },

    goHome: function () {
      if (location.hash) {
        location.hash = '';
      } else {
        // Already home — nothing to change, but still let the caller’s
        // logic run (e.g. re-showing search results) without adding a
        // redundant history entry.
        dispatch();
      }
    }

  };
})();
