/* Auto-generated by generate_site.py — edits here are overwritten on the
   next run. Edit SERVICE_WORKER_TEMPLATE in generate_site.py instead.
   Exception: change the number BEFORE the "." in SW_VERSION by hand to
   jump a major version; the generator only bumps the part after it. */

const SW_VERSION = "jacaranda-dark-ui-v1.007";

// Versioned: replaced on every run. Holds the app shell + every template.
const CORE_CACHE = "core-" + SW_VERSION;

// NOT versioned: must survive updates, or every generator run would
// wipe the downloaded images.
const IMAGE_CACHE = "imgcatch";
const IMAGE_MAX_BYTES = 2 * 1024 * 1024;

// Everything is resolved against the SW scope, so the site works from any
// base path (e.g. https://user.github.io/vedana/).
const SCOPE = self.registration.scope;
const PRECACHE_URLS = [
  "css/styles.css",
  "fonts/CharisSIL-Bold.woff2",
  "fonts/CharisSIL-BoldItalic.woff2",
  "fonts/CharisSIL-Italic.woff2",
  "fonts/CharisSIL-Regular.woff2",
  "fonts/LibreBaskerville-Bold.woff2",
  "fonts/LibreBaskerville-BoldItalic.woff2",
  "fonts/LibreBaskerville-Italic.woff2",
  "fonts/LibreBaskerville-Regular.woff2",
  "fonts/NunitoSans-Bold.woff2",
  "fonts/NunitoSans-BoldItalic.woff2",
  "fonts/NunitoSans-Italic.woff2",
  "fonts/NunitoSans-Regular.woff2",
  "img/author_avatar.jpg",
  "img/author_avy.jpg",
  "img/author_photo.jpg",
  "img/author_picture.jpg",
  "img/rk_bhojan-lila-on-yamuna.jpg",
  "img/rk_nikunj-rasa.jpg",
  "img/rk_purva-raga.jpg",
  "img/rk_vina.jpg",
  "index.html",
  "js/app.js",
  "js/dependencies/fuse.min.js",
  "js/router.js",
  "site.webmanifest",
  "templates/datos-importantes/envidia-matsarya.html",
  "templates/datos-importantes/glosario-de-terminos.html",
  "templates/gaudiya-acaryas/prabhupada-aparicion.html",
  "templates/jaiva-dharma-i/intro-001.html",
  "templates/jaiva-dharma-i/intro-002.html",
  "templates/jaiva-dharma-i/intro-003.html",
  "templates/jaiva-dharma-iii/jaiva-dharma-40.html",
  "templates/krsna-dasavatara/baladeva-tattva.html",
  "templates/radha-y-krsna/janmastami-2.html",
  "templates/radha-y-krsna/janmastami-3.html",
  "templates/radha-y-krsna/janmastami-4.html",
  "templates/radha-y-krsna/janmastami.html",
  "templates/radha-y-krsna/radhastami-2.html",
  "templates/radha-y-krsna/radhastami.html",
  "templates/radha-y-krsna/stava-stutis.html",
  "templates/search-index.json"
];
const PRECACHE_HREFS = new Set(
  PRECACHE_URLS.map(function (path) {
    return new URL(path, SCOPE).href;
  })
);
const INDEX_HREF = new URL("index.html", SCOPE).href;
const IMGCATCH_PREFIX = new URL("imgcatch/", SCOPE).href;

self.addEventListener("install", function (event) {
  event.waitUntil(
    Promise.all([
      caches.open(CORE_CACHE).then(function (cache) {
        // cache:"reload" bypasses the HTTP cache so a new version never
        // precaches stale copies of its own files.
        return cache.addAll(
          PRECACHE_URLS.map(function (path) {
            return new Request(new URL(path, SCOPE).href, { cache: "reload" });
          })
        );
      }),
      // Created empty on install; filled on demand as slugs load images.
      caches.open(IMAGE_CACHE)
    ])
  );
});

self.addEventListener("activate", function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys
          .filter(function (key) {
            return key.indexOf("core-") === 0 && key !== CORE_CACHE;
          })
          .map(function (key) {
            return caches.delete(key);
          })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

self.addEventListener("message", function (event) {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// ---- Image cache: 2 MB cap, least-recently-used entries evicted first ----

// Serializes store/trim work so concurrent image loads can't race.
var imageQueue = Promise.resolve();

function enqueue(task) {
  imageQueue = imageQueue.then(task).catch(function () {});
  return imageQueue;
}

async function trimImageCache(cache) {
  var entries = [];
  var total = 0;
  var requests = await cache.keys();

  for (var i = 0; i < requests.length; i++) {
    var response = await cache.match(requests[i]);
    if (!response) continue;

    var size = Number(response.headers.get("X-Img-Size")) || 0;
    var lastUsed = Number(response.headers.get("X-Img-Last-Used")) || 0;

    total += size;
    entries.push({ request: requests[i], size: size, lastUsed: lastUsed });
  }

  entries.sort(function (a, b) {
    return a.lastUsed - b.lastUsed;
  });

  while (total > IMAGE_MAX_BYTES && entries.length) {
    var victim = entries.shift();
    await cache.delete(victim.request);
    total -= victim.size;
  }
}

// Used both for the first download and to refresh "last used" on a hit.
async function storeImage(request, source, cache) {
  var body = await source.arrayBuffer();

  if (body.byteLength > IMAGE_MAX_BYTES) return;

  var headers = new Headers();
  headers.set("Content-Type", source.headers.get("Content-Type") || "application/octet-stream");
  headers.set("X-Img-Size", String(body.byteLength));
  headers.set("X-Img-Last-Used", String(Date.now()));

  await cache.put(request, new Response(body, { status: 200, headers: headers }));
  await trimImageCache(cache);
}

async function handleImage(event) {
  var request = event.request;
  var cache = await caches.open(IMAGE_CACHE);
  var cached = await cache.match(request);

  if (cached) {
    var forTouch = cached.clone(); // clone BEFORE the page consumes it
    event.waitUntil(enqueue(function () {
      return storeImage(request, forTouch, cache);
    }));
    return cached;
  }

  try {
    var response = await fetch(request);

    if (response.status === 200) {
      var forStore = response.clone(); // clone BEFORE returning
      event.waitUntil(enqueue(function () {
        return storeImage(request, forStore, cache);
      }));
    }

    return response;
  } catch (error) {
    // Offline and not cached: app.js shows the "image will be visible
    // when back online" note when the <img> fails.
    return new Response("", { status: 504, statusText: "Offline" });
  }
}

// ---- Routing ----

self.addEventListener("fetch", function (event) {
  var request = event.request;

  if (request.method !== "GET") return;

  var url = new URL(request.url);

  // Remote resources: browser default.
  if (url.origin !== self.location.origin) return;

  var key = url.origin + url.pathname; // ignores ?query and #hash

  if (url.href.indexOf(IMGCATCH_PREFIX) === 0) {
    event.respondWith(handleImage(event));
    return;
  }

  if (PRECACHE_HREFS.has(key)) {
    event.respondWith(
      caches.open(CORE_CACHE).then(function (cache) {
        return cache.match(key).then(function (cached) {
          return cached || fetch(request);
        });
      })
    );
    return;
  }

  if (request.mode === "navigate") {
    event.respondWith(
      caches.open(CORE_CACHE).then(function (cache) {
        return cache.match(INDEX_HREF).then(function (cached) {
          return cached || fetch(request);
        });
      })
    );
  }
});
